---
name: entropy-check

on:
  push:
    branches:
      - main
      - GitHub-Action
  pull_request:
    branches:
      - main
      - GitHub-Action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install

      - name: Process repository entropy
        run: poetry run almanack process_repo_entropy . > entropy_report.txt

      - name: Encode and Save Report
        run: |
          base64_entropy_report=$(base64 -w 0 entropy_report.txt)
          echo "BASE64_REPORT=$base64_entropy_report" >> $GITHUB_ENV

      - name: Post Entropy Report
        uses: thollander/actions-comment-pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT: |
            Entropy Report:
            ```
            $(echo ${{ env.BASE64_REPORT }} | base64 --decode)
